### PR TITLE
Improve domain validation

### PR DESCRIPTION
**Pull request by camlafit**
Following informations provided at https://en.wikipedia.org/wiki/Domain_Name_System#cite_ref-rfc3696_28-0
* domain name can't be exceed  253 caracters
* maximum label are 127
* last label can't (should not) be all numeric
* ignore before last label capturing group

### CODE REVIEW

**Comment by zapalm** [comment]
Thank you for your pull request.
1. There is a mistake with a param.
2. It is needed to improve the test for each new rule added and then run the test to ensure that all right: https://github.com/zapalm/prestashop-helpers/blob/85e027c81f4434b11a307e671dab6358496807a4/tests/ValidateHelperTest.php#L61
3. You have added a new line in the end of file. It is not allowed by the PSR standard.

**Comment by camlafit** [comment]
Hello

I prepare a PR rework to publish some step and provide some related tests

Thanks

**Comment by camlafit** [comment]
Hello

PR was reworked to split all steps about domain validation with tests.
It's based on **master** but I do a check and should be ok over **dev** branch also

I hope it's more explicit

**Comment by camlafit** [comment]
Ok github allow to change PR source branch. 
Now it's rebased over dev as asked on readme.

**Comment by camlafit** [comment]
Hello

Have you got time to review this PR ?

**Review by zapalm — CHANGES_REQUESTED** [review]
Oh, sorry. I forgot to click the "Request changes" button. I reviewed your PR in July and waited for your response ;)
I have some suggestions on how to improve the test. If you agree, I can make these changes in your PR to speed up the merge.

**Comment by camlafit** [comment]
thanks a lot :)

**Pull request merged**
